In [2]:
import pandas as pd

# 名前、値段、重さ(g)のデータ
df = pd.read_csv('data/items.csv')
df

   Name  Price  Weight  ShippingCost
0  小麦粉A    100     200          1000
1  小麦粉A    150     500          1000
2  小麦粉A    290    1000          1000
3  小麦粉B    130     300           500
4  小麦粉C    260     900          1200

In [3]:
# 列Makerの追加
df['Maker'] = ['メーカーA', 'メーカーA', 'メーカーA', 'メーカーB', 'メーカーC']
df

   Name  Price  Weight  ShippingCost  Maker
0  小麦粉A    100     200          1000  メーカーA
1  小麦粉A    150     500          1000  メーカーA
2  小麦粉A    290    1000          1000  メーカーA
3  小麦粉B    130     300           500  メーカーB
4  小麦粉C    260     900          1200  メーカーC

In [4]:
# 列nameの変更
df['Name'] = ['小麦粉A 200g', '小麦粉A 500g', '小麦粉A 1000g', '小麦粉B 300g', '小麦粉C 900g']
df

         Name  Price  Weight  ShippingCost  Maker
0   小麦粉A 200g    100     200          1000  メーカーA
1   小麦粉A 500g    150     500          1000  メーカーA
2  小麦粉A 1000g    290    1000          1000  メーカーA
3   小麦粉B 300g    130     300           500  メーカーB
4   小麦粉C 900g    260     900          1200  メーカーC

In [5]:
# 計算結果を列weight_kgとして追加
df['WeightKg'] = df['Weight'] / 1000
df

         Name  Price  Weight  ShippingCost  Maker  WeightKg
0   小麦粉A 200g    100     200          1000  メーカーA       0.2
1   小麦粉A 500g    150     500          1000  メーカーA       0.5
2  小麦粉A 1000g    290    1000          1000  メーカーA       1.0
3   小麦粉B 300g    130     300           500  メーカーB       0.3
4   小麦粉C 900g    260     900          1200  メーカーC       0.9

In [6]:
# 計算結果を列price_per_kgとして追加
df['PricePerKg'] = df['Price'] / df['WeightKg']
df

         Name  Price  Weight  ShippingCost  Maker  WeightKg  PricePerKg
0   小麦粉A 200g    100     200          1000  メーカーA       0.2  500.000000
1   小麦粉A 500g    150     500          1000  メーカーA       0.5  300.000000
2  小麦粉A 1000g    290    1000          1000  メーカーA       1.0  290.000000
3   小麦粉B 300g    130     300           500  メーカーB       0.3  433.333333
4   小麦粉C 900g    260     900          1200  メーカーC       0.9  288.888889

In [7]:
# 列price_per_kgのランクを新しい列 price_rankとして追加
df['PriceRank'] = df['PricePerKg'].rank()
df

,Name,Price,Weight,ShippingCost,Maker,WeightKg,PricePerKg,PriceRank
0,小麦粉A 200g,100,200,1000,メーカーA,0.2,500.000000,5.0
1,小麦粉A 500g,150,500,1000,メーカーA,0.5,300.000000,3.0
2,小麦粉A 1000g,290,1000,1000,メーカーA,1.0,290.000000,2.0
3,小麦粉B 300g,130,300,500,メーカーB,0.3,433.333333,4.0
4,小麦粉C 900g,260,900,1200,メーカーC,0.9,288.888889,1.0